# Generated by Django 3.0.4 on 2020-03-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('picture', models.FileField(upload_to='images/')),
                ('picture_ind', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
