# Generated by Django 3.0.4 on 2020-03-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_remove_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture_ind',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
