# Generated by Django 3.0.4 on 2020-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20200323_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='persons_key',
            field=models.PositiveSmallIntegerField(default='1111'),
        ),
    ]
